# Generated by Django 3.1 on 2020-11-14 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20201114_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmwork',
            old_name='pople',
            new_name='people',
        ),
    ]
