# Generated by Django 3.1 on 2020-11-15 00:12

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20201114_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='movies.person')),
            ],
            bases=('movies.person',),
            managers=[
                ('movies', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='movies',
            field=models.ManyToManyField(related_name='films', through='movies.PersonFilmWork', to='movies.FilmWork'),
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='genre',
            field=models.ManyToManyField(related_name='genres', through='movies.GenreFilmWork', to='movies.Genre'),
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='people',
            field=models.ManyToManyField(related_name='people', through='movies.PersonFilmWork', to='movies.Person'),
        ),
    ]
