# Generated by Django 3.1 on 2020-11-15 12:55

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20201115_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='movies',
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('movies.person',),
            managers=[
                ('movies', django.db.models.manager.Manager()),
            ],
        ),
    ]
