version: '3.7'
services:
  db:
    image: postgres:latest
    container_name: postgres
    network_mode: bridge
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432
    volumes:
      - ./movies_admin/load_data/movies.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    build: .
    container_name: django
    network_mode: bridge
    command:
        bash -c "python ./load_data/load_data.py
      && python ./manage.py migrate --fake movies 0001_initial
      && python ./manage.py migrate
      && python ./manage.py collectstatic
      && python ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./static/:/static
    expose:
      - "8000"
    depends_on:
      - db
    links:
      - db
    restart: on-failure
  nginx:
    image: nginx:1.19.2
    container_name: nginx
    network_mode: bridge
    volumes:
      - ./src/nginx.conf:/src/nginx.conf:ro
      - ./etc/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./static:/static
    depends_on:
      - web
    ports:
      - "8000:8000"
    links:
      - web
    restart: on-failure
